import fs from 'fs';
import https from 'https';

const content = fs.readFileSync('src/data/aircrafts.js', 'utf8');
const jsonStr = content.substring(content.indexOf('['), content.lastIndexOf(']') + 1);
const aircrafts = JSON.parse(jsonStr);

// Hard map specific aircraft to their EXACT Wikipedia page titles which are guaranteed to have a main infobox image
const pageMap = {
  "Airbus A340-500": "Airbus_A340",
  "Airbus A340-600": "Airbus_A340",
  "Antonov An-124-100": "Antonov_An-124_Ruslan",
  "Avro Vulcan B.1": "Avro_Vulcan",
  "Avro Vulcan B.2": "Avro_Vulcan",
  "Beechcraft King Air B200": "Beechcraft_Super_King_Air",
  "Boeing 737-600": "Boeing_737_Next_Generation",
  "Boeing 747-300": "Boeing_747",
  "Boeing 777-300": "Boeing_777",
  "Boeing 777-9": "Boeing_777X",
  "Bombardier Global 7500": "Bombardier_Global_Express",
  "Cessna Citation X": "Cessna_Citation_X",
  "Dassault Mirage 2000D": "Dassault_Mirage_2000",
  "Embraer E175-200": "Embraer_E-Jet_family",
  "Mikoyan-Gurevich MiG-17F": "Mikoyan-Gurevich_MiG-17",
  "Sukhoi Su-34": "Sukhoi_Su-34",
  "Lockheed Martin F-16V Block 70" : "General_Dynamics_F-16_Fighting_Falcon",
  "Mikoyan MiG-29K": "Mikoyan_MiG-29K"
};

const getSummaryImage = (pageTitle) => {
  return new Promise((resolve) => {
    const url = `https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(pageTitle)}`;
    https.get(url, { headers: { 'User-Agent': 'AircraftCompareBot/6.0' } }, (res) => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {
        try {
          const json = JSON.parse(data);
          if (json.originalimage && json.originalimage.source) {
             resolve(json.originalimage.source);
          } else if (json.thumbnail && json.thumbnail.source) {
             resolve(json.thumbnail.source);
          } else {
             resolve(null);
          }
        } catch (e) {
          resolve(null);
        }
      });
    }).on('error', () => resolve(null));
  });
};

const run = async () => {
    let count = 0;
    for (const plane of aircrafts) {
        if (pageMap[plane.name]) {
            const img = await getSummaryImage(pageMap[plane.name]);
            if (img) {
                // Remove the restrictive thumb limits if generated by page/summary, just use original
                plane.image = img;
                console.log(`[SUCCESS] Patched ${plane.name} with ${img}`);
                count++;
            } else {
                console.log(`[FAILED] No image found on Wikipedia page for ${pageMap[plane.name]}`);
            }
        }
    }

    const newContent = 'export const aircrafts = ' + JSON.stringify(aircrafts, null, 2) + ';';
    fs.writeFileSync('src/data/aircrafts.js', newContent);
    console.log(`Successfully hard-linked ${count} Wikipedia Infobox images using the REST API.`);
};

run();
